In [276]:
import pandas as pd
import numpy as np

In [277]:
ratings = pd.read_csv('../dataset/ratings.csv', usecols=['userId','movieId','rating'])
movies = pd.read_csv('../dataset/movies.csv',usecols=['movieId','title','genres'])
print(ratings)
print(movies)

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]
      movieId                                      title  \
0           1                           Toy Story (1995)
1           2                             Jumanji (1995)
2           3                    Grumpier Old Men (1995)
3           4                   Waiting to Exhale (1995)
4           5         Father of the Bride Part II (1995)
...       ...                                        ...
9737   193581  Black Butler: Book of the Atlantic (2017)
9738   193583               No Game No Life: Zero (2017)
9739   193585                               Flint (2017)
9740   193587        Bungo Stray Dogs: Dead Apple (2018)
9741   193609        Andrew Dice Clay: Dice Rules (1991)

                                           genres
0     Adventure|Animation|Children|Comedy|Fantasy
1                      Adventure|Children|Fantasy
2                                  Comedy|Romance
3                            Comedy|Drama|Romance
4                                          Comedy
...                                           ...
9737              Action|Animation|Comedy|Fantasy
9738                     Animation|Comedy|Fantasy
9739                                        Drama
9740                             Action|Animation
9741                                       Comedy

[9742 rows x 3 columns]

In [278]:
merged_ratings = pd.merge(ratings, movies, how='inner', on='movieId')
print(merged_ratings)

        userId  movieId  rating                             title  \
0            1        1     4.0                  Toy Story (1995)
1            5        1     4.0                  Toy Story (1995)
2            7        1     4.5                  Toy Story (1995)
3           15        1     2.5                  Toy Story (1995)
4           17        1     4.5                  Toy Story (1995)
...        ...      ...     ...                               ...
100831     610   160341     2.5                  Bloodmoon (1997)
100832     610   160527     4.5  Sympathy for the Underdog (1971)
100833     610   160836     3.0                     Hazard (2005)
100834     610   163937     3.5                Blair Witch (2016)
100835     610   163981     3.5                         31 (2016)

                                             genres
0       Adventure|Animation|Children|Comedy|Fantasy
1       Adventure|Animation|Children|Comedy|Fantasy
2       Adventure|Animation|Children|Comedy|Fantasy
3       Adventure|Animation|Children|Comedy|Fantasy
4       Adventure|Animation|Children|Comedy|Fantasy
...                                             ...
100831                              Action|Thriller
100832                           Action|Crime|Drama
100833                        Action|Drama|Thriller
100834                              Horror|Thriller
100835                                       Horror

[100836 rows x 5 columns]

In [279]:
final_ratings = merged_ratings.pivot_table(index = 'title',columns='userId',values='rating',fill_value=0)
print(final_ratings)

userId                                     1    2    3    4    5    6    7    \
title
'71 (2014)                                   0  0.0  0.0    0    0    0  0.0
'Hellboy': The Seeds of Creation (2004)      0  0.0  0.0    0    0    0  0.0
'Round Midnight (1986)                       0  0.0  0.0    0    0    0  0.0
'Salem's Lot (2004)                          0  0.0  0.0    0    0    0  0.0
'Til There Was You (1997)                    0  0.0  0.0    0    0    0  0.0
...                                        ...  ...  ...  ...  ...  ...  ...
eXistenZ (1999)                              0  0.0  0.0    0    0    0  0.0
xXx (2002)                                   0  0.0  0.0    0    0    0  0.0
xXx: State of the Union (2005)               0  0.0  0.0    0    0    0  0.0
¡Three Amigos! (1986)                        4  0.0  0.0    0    0    0  0.0
À nous la liberté (Freedom for Us) (1931)    0  0.0  0.0    0    0    0  0.0

userId                                     8    9    10   ...  601  602  603  \
title                                                     ...
'71 (2014)                                   0    0  0.0  ...  0.0    0    0
'Hellboy': The Seeds of Creation (2004)      0    0  0.0  ...  0.0    0    0
'Round Midnight (1986)                       0    0  0.0  ...  0.0    0    0
'Salem's Lot (2004)                          0    0  0.0  ...  0.0    0    0
'Til There Was You (1997)                    0    0  0.0  ...  0.0    0    0
...                                        ...  ...  ...  ...  ...  ...  ...
eXistenZ (1999)                              0    0  0.0  ...  0.0    0    5
xXx (2002)                                   0    1  0.0  ...  0.0    0    0
xXx: State of the Union (2005)               0    0  0.0  ...  0.0    0    0
¡Three Amigos! (1986)                        0    0  0.0  ...  0.0    0    0
À nous la liberté (Freedom for Us) (1931)    0    0  0.0  ...  0.0    0    0

userId                                     604  605  606  607  608  609  610
title
'71 (2014)                                   0  0.0  0.0    0  0.0    0  4.0
'Hellboy': The Seeds of Creation (2004)      0  0.0  0.0    0  0.0    0  0.0
'Round Midnight (1986)                       0  0.0  0.0    0  0.0    0  0.0
'Salem's Lot (2004)                          0  0.0  0.0    0  0.0    0  0.0
'Til There Was You (1997)                    0  0.0  0.0    0  0.0    0  0.0
...                                        ...  ...  ...  ...  ...  ...  ...
eXistenZ (1999)                              0  0.0  0.0    0  4.5    0  0.0
xXx (2002)                                   0  0.0  0.0    0  3.5    0  2.0
xXx: State of the Union (2005)               0  0.0  0.0    0  0.0    0  1.5
¡Three Amigos! (1986)                        0  0.0  0.0    0  0.0    0  0.0
À nous la liberté (Freedom for Us) (1931)    0  0.0  0.0    0  0.0    0  0.0

[9719 rows x 610 columns]

In [280]:
final_ratings.index

Index([''71 (2014)', ''Hellboy': The Seeds of Creation (2004)',
       ''Round Midnight (1986)', ''Salem's Lot (2004)',
       ''Til There Was You (1997)', ''Tis the Season for Love (2015)',
       ''burbs, The (1989)', ''night Mother (1986)',
       '(500) Days of Summer (2009)', '*batteries not included (1987)',
       ...
       'Zulu (2013)', '[REC] (2007)', '[REC]² (2009)',
       '[REC]³ 3 Génesis (2012)',
       'anohana: The Flower We Saw That Day - The Movie (2013)',
       'eXistenZ (1999)', 'xXx (2002)', 'xXx: State of the Union (2005)',
       '¡Three Amigos! (1986)', 'À nous la liberté (Freedom for Us) (1931)'],
      dtype='object', name='title', length=9719)

In [281]:
from sklearn.neighbors import NearestNeighbors

In [282]:
def addUser(df,rating_list):
    print(len(df.columns.tolist()))
    df[(len(df.columns.tolist())+1)] = rating_list

In [283]:
ratings_user = list(np.zeros(len(final_ratings.index)))
ratings_user[3] = 3
addUser(final_ratings,ratings_user)
display(final_ratings)

610

userId,1,2,3,4,5,6,7,8,9,10,...,602,603,604,605,606,607,608,609,610,611
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),0,0.0,0.0,0,0,0,0.0,0,0,0.0,...,0,0,0,0.0,0.0,0,0.0,0,4.0,0.0
'Hellboy': The Seeds of Creation (2004),0,0.0,0.0,0,0,0,0.0,0,0,0.0,...,0,0,0,0.0,0.0,0,0.0,0,0.0,0.0
'Round Midnight (1986),0,0.0,0.0,0,0,0,0.0,0,0,0.0,...,0,0,0,0.0,0.0,0,0.0,0,0.0,0.0
'Salem's Lot (2004),0,0.0,0.0,0,0,0,0.0,0,0,0.0,...,0,0,0,0.0,0.0,0,0.0,0,0.0,3.0
'Til There Was You (1997),0,0.0,0.0,0,0,0,0.0,0,0,0.0,...,0,0,0,0.0,0.0,0,0.0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
eXistenZ (1999),0,0.0,0.0,0,0,0,0.0,0,0,0.0,...,0,5,0,0.0,0.0,0,4.5,0,0.0,0.0
xXx (2002),0,0.0,0.0,0,0,0,0.0,0,1,0.0,...,0,0,0,0.0,0.0,0,3.5,0,2.0,0.0
xXx: State of the Union (2005),0,0.0,0.0,0,0,0,0.0,0,0,0.0,...,0,0,0,0.0,0.0,0,0.0,0,1.5,0.0
¡Three Amigos! (1986),4,0.0,0.0,0,0,0,0.0,0,0,0.0,...,0,0,0,0.0,0.0,0,0.0,0,0.0,0.0
À nous la liberté (Freedom for Us) (1931),0,0.0,0.0,0,0,0,0.0,0,0,0.0,...,0,0,0,0.0,0.0,0,0.0,0,0.0,0.0

In [284]:
print(final_ratings.values.shape)
k = 5
knn = NearestNeighbors(metric = 'cosine', algorithm='brute')
knn.fit(final_ratings.values)

(9719, 611)

NearestNeighbors(algorithm='brute', metric='cosine')

In [285]:
differences,movie_indices = distances, indices = knn.kneighbors(final_ratings.values, n_neighbors=k)
print(type(differences))

<class 'numpy.ndarray'>

In [286]:
print(movie_indices)

[[2397 2398 8806 4425 8807]
 [   1 7888 5773  362 3913]
 [   2  278  623  507  531]
 ...
 [9716 8324 6866 4889 2179]
 [9717 5753 3294 3548 3618]
 [8255 5990 9718 3144 3044]]

In [287]:
final_ratings_copy = final_ratings.copy()

In [288]:
print(final_ratings.columns.to_list())

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611]

In [289]:
def print_recommendations(user,num_recommended_movies):
  print('The list of the Movies {} Has Watched \n'.format(user))

  for m in final_ratings[final_ratings[user] > 0][user].index.tolist():
    print(m)
  
  print('\n')

  recommended_movies = []

  for m in final_ratings[final_ratings[user] == 0].index.tolist():

    index_df = final_ratings.index.tolist().index(m)
    predicted_rating = final_ratings_copy.iloc[index_df, final_ratings_copy.columns.tolist().index(user)]
    recommended_movies.append((m, predicted_rating))

  sorted_rm = sorted(recommended_movies, key=lambda x:x[1], reverse=True)
  
  print('The list of the Recommended Movies \n')
  rank = 1
  for recommended_movie in sorted_rm[:num_recommended_movies]:
    
    print('{}: {} - predicted rating:{}'.format(rank, recommended_movie[0], recommended_movie[1]))
    rank = rank + 1

In [290]:
def CF_engine(userID,k,numrec):
    knn_obj = NearestNeighbors(metric = 'cosine',algorithm='brute')
    knn_obj.fit(final_ratings.values)
    differences,movie_indices = knn_obj.kneighbors(final_ratings.values,n_neighbors=k)
    user_index=final_ratings.columns.tolist().index(userID)
    

    for movie,title in list(enumerate(final_ratings_copy.index)):
        if(final_ratings_copy.iloc[movie,user_index] == 0):
            similar_movie_indices = movie_indices[movie].tolist()
            similar_movie_distances = differences[movie].tolist()

            if movie in similar_movie_indices:
                movieId = similar_movie_indices.index(movie)
                similar_movie_indices.remove(movie)
                similar_movie_distances.pop(movieId) 

            # However, if the percentage of ratings in the dataset is very low, there are too many 0s in the dataset. 
            # Some movies have all 0 ratings and the movies with all 0s are considered the same movies by NearestNeighbors(). 
            # Then,even the movie itself cannot be included in the indices. 
            # For example, indices[3] = [2 4 7] is possible if movie_2, movie_3, movie_4, and movie_7 have all 0s for their ratings.
            # In that case, we take off the farthest movie in the list. Therefore, 7 is taken off from the list, then indices[3] == [2 4].
            else:
                similar_movie_indices = similar_movie_indices[:k-1]
                similar_movie_distances = similar_movie_distances[:k-1]
                
            # movie_similarty = 1 - movie_distance    
            closeness = [1-x for x in similar_movie_distances]
            closeness_copy = closeness.copy()
            weighted_sum = 0

        # for each similar movie
            for s in range(0, len(closeness)):
            
            # check if the rating of a similar movie is zero
                if final_ratings_copy.iloc[similar_movie_indices[s], user_index] == 0:
                    # if the rating is zero, ignore the rating and the similarity in calculating the predicted rating
                    if len(closeness_copy) == (k - 1):
                        closeness_copy.pop(s)
                    
                    else:
                        closeness_copy.pop(s-(len(closeness)-len(closeness_copy)))

                # if the rating is not zero, use the rating and similarity in the calculation
                else:
                    weighted_sum = weighted_sum + closeness[s]*final_ratings_copy.iloc[similar_movie_indices[s],user_index]

                # check if the number of the ratings with non-zero is positive
                if len(closeness_copy) > 0:
                
                # check if the sum of the ratings of the similar movies is positive.
                    if sum(closeness_copy) > 0:
                        pred_rating = weighted_sum/sum(closeness_copy)

                    # Even if there are some movies for which the ratings are positive, some movies have zero similarity even though they are selected as similar movies.
                    # in this case, the predicted rating becomes zero as well  
                    else:
                        pred_rating = 0

                # if all the ratings of the similar movies are zero, then predicted rating should be zero
                else:
                    pred_rating = 0

    # place the predicted rating into the copy of the original dataset
            final_ratings_copy.iloc[movie,user_index] = pred_rating
    print_recommendations(userID,numrec)

In [291]:
CF_engine(611, 10, 10)

The list of the Movies 611 Has Watched

'Salem's Lot (2004)


The list of the Recommended Movies

1: All the President's Men (1976) - predicted rating:3.0000000000000004
2: Get on Up (2014) - predicted rating:3.0000000000000004
3: Guess Who's Coming to Dinner (1967) - predicted rating:3.0000000000000004
4: Harvey (1950) - predicted rating:3.0000000000000004
5: Kramer vs. Kramer (1979) - predicted rating:3.0000000000000004
6: Mr. Smith Goes to Washington (1939) - predicted rating:3.0000000000000004
7: Officer and a Gentleman, An (1982) - predicted rating:3.0000000000000004
8: Rebecca (1940) - predicted rating:3.0000000000000004
9: Rosemary's Baby (1968) - predicted rating:3.0000000000000004
10: Sabrina (1954) - predicted rating:3.0000000000000004

In [292]:
def return_similar_movie(movie_index):
    # movie_index = final_ratings.index.tolist().index(title)
    similar_movie_indices = movie_indices[movie_index].tolist()
    similar_movie_distances = differences[movie_index].tolist()
    movie_pos = similar_movie_indices.index(movie_index) # find the index of the movie itself , since it is the closest neighbour this will always be 0 

    similar_movie_indices.remove(movie_index) # remove the movie itself in indices
    similar_movie_distances.pop(movie_pos) # remove the movie itself in distances

    print("The Movies that are quite Similar to " , final_ratings.index[movie_index])
    for i in similar_movie_indices:
        movie_title = final_ratings.index[i]
        print(str(i+1) + ": " + movie_title) 

    #now, we must remove the movie itslef from this slist ( as a movie is always similar to itself)

In [293]:
return_similar_movie(6)

The Movies that are quite Similar to  'burbs, The (1989)
743: Back to School (1986)
5754: Money Pit, The (1986)
609: Arthur (1981)
593: Armed and Dangerous (1986)

In [294]:
k = final_ratings.index.to_list()
print(type(k))
print(k[6])

<class 'list'>
'burbs, The (1989)

In [295]:
# can i add a row to the ratings?!!
print(type(final_ratings))

<class 'pandas.core.frame.DataFrame'>